USE [master]
GO

/****** Object:  Database [CDS]    Script Date: 7/17/2024 3:48:22 PM ******/
CREATE DATABASE [CDS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CDS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CDS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CDS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CDS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CDS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CDS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CDS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CDS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CDS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CDS] SET ARITHABORT OFF 
GO

ALTER DATABASE [CDS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CDS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CDS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CDS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CDS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CDS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CDS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CDS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CDS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CDS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CDS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CDS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CDS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CDS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CDS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CDS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CDS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CDS] SET RECOVERY FULL 
GO

ALTER DATABASE [CDS] SET  MULTI_USER 
GO

ALTER DATABASE [CDS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CDS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CDS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CDS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CDS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CDS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CDS] SET QUERY_STORE = ON
GO

ALTER DATABASE [CDS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CDS] SET  READ_WRITE 
GO




USE [CDS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATEGORY](
	[CATEGORY_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[CATEGORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UN_CATEGORY] UNIQUE NONCLUSTERED 
(
	[CATEGORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PRODUCT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FULL_NAME] [varchar](50) NOT NULL,
	[DISPLAY_NAME] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](250) NOT NULL,
	[PRICE] [decimal](18, 0) NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CREATION_DATE] [datetime] NOT NULL,
	[EXPIRATION_DATE] [datetime] NOT NULL,
	[CATEGORY_ID] [int] NOT NULL,
	[AVAILABLE_QTY] [int] NOT NULL,
	[LAST_MODIFICATION_DATE] [datetime] NOT NULL,
	[IS_DELETED] [bit] NOT NULL,
	[DELETED_DATE] [datetime] NULL,
 CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UN_PRODUCT] UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUCT] ADD  CONSTRAINT [DF_PRODUCT_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO

ALTER TABLE [dbo].[PRODUCT] ADD  CONSTRAINT [DF_PRODUCT_IS_DELETED]  DEFAULT ((0)) FOR [IS_DELETED]
GO

ALTER TABLE [dbo].[PRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCT_CATEGORY] FOREIGN KEY([CATEGORY_ID])
REFERENCES [dbo].[CATEGORY] ([CATEGORY_ID])
GO

ALTER TABLE [dbo].[PRODUCT] CHECK CONSTRAINT [FK_PRODUCT_CATEGORY]
GO

INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Ropa y Accesorios');
INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Electrónica');
INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Hogar y Jardín');
INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Salud y Belleza');
INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Deportes y Aire Libre');
INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Juguetes y Juegos');
INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Libros y Medios');
INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Automotriz');
INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Suministros de Oficina');
INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Alimentos y Bebidas');
INSERT INTO [dbo].[CATEGORY] ([NAME]) VALUES ('Productos para Mascotas');

INSERT INTO [dbo].[PRODUCT]
       ([FULL_NAME]
       ,[DISPLAY_NAME]
       ,[DESCRIPTION]
       ,[PRICE]
       ,[CREATION_DATE]
       ,[EXPIRATION_DATE]
       ,[CATEGORY_ID]
       ,[AVAILABLE_QTY]
       ,[LAST_MODIFICATION_DATE]
       ,[DELETED_DATE])
VALUES
       ('Laptop',            -- FULL_NAME
        'ASUS ROG',                    -- DISPLAY_NAME
        'Gaming laptop with high performance',  -- DESCRIPTION
        1999.99,                          -- PRICE
        GETDATE(),                      -- CREATION_DATE (current date/time)
        GETDATE(),                           -- EXPIRATION_DATE (if not applicable or set later)
        2,                              -- CATEGORY_ID (assuming category ID 1)
        5,                            -- AVAILABLE_QTY (assuming 100 units available)
        GETDATE(),                      -- LAST_MODIFICATION_DATE (initial creation date)
        NULL                            -- DELETED_DATE (NULL if not deleted)
       );
GO